
services:
  tron-node1:
    container_name: tron-node1
    image: tronprotocol/java-tron:latest  # Add specific tag if needed
    mem_limit: 64g
    ports:
      - "8090:8090"
      - "8545:8545"
    volumes:
      - /tron/output-directory:/java-tron/output-directory
      - /tron/logs:/java-tron/logs
      - /tron/config:/java-tron/config
    command:
      - -jvm
      - "{-Xmx64g -Xms32g -XX:+UseConcMarkSweepGC}"  # Using environment variable for JVM arguments
      - -c
      - /java-tron/config/main_net_config.conf

  tron-node2:
    container_name: tron-node2-read-only
    image: tronprotocol/java-tron:latest  # Add specific tag if needed
    mem_limit: 64g
    ports:
      - "28090:8090"
      - "28545:8545"
    volumes:
      - /tron2/output-directory:/java-tron/output-directory
      - /tron2/logs:/java-tron/logs
      - /tron2/config:/java-tron/config
    command:
      - -jvm
      - "{-Xmx64g -Xms32g -XX:+UseConcMarkSweepGC}"  # Using environment variable for JVM arguments
      - -c
      - /java-tron/config/main_net_config.conf
    